# Generated by Django 3.0.4 on 2020-04-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200401_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativa',
            name='poblacion_estimada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poblacion',
            name='vulnerable',
            field=models.BooleanField(default=False),
        ),
    ]
