# Generated by Django 3.0.4 on 2020-04-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200401_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativa',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
