# Generated by Django 3.0.4 on 2020-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200404_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativa',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='link_image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='nombre',
            field=models.TextField(null=True),
        ),
    ]
